name: 'synched-support'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - notebook
    - pyarrow
    - altair
    - dash
    - dash-bootstrap-components
    - plotly
    - pip
    - urllib3
    - matplotlib
    - pandas
    - pip:
        - dash-vega-components